<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Beschreibung' => 'Beschreibung',
    'Create Projekt' => 'Projekt anlegen',
    'Delete' => 'Löschen',
    'Entwickler' => 'Entwickler',
    'ID' => 'ID',
    'Name' => 'Name',
    'Projekt' => 'Projekt',
    'Projekt ID' => 'Projekt ID',
    'Projektleiter' => 'Projektleiter',
    'Projektnutzer' => 'Projektnutzer',
    'Projekts' => 'Projekte',
    'Reporter' => 'Reporter',
    'Reset' => 'Zurücksetzen',
    'Rolle' => 'Rolle',
    'Save' => 'Speichern',
    'Search' => 'Suchen',
    'The requested page does not exist.' => 'Die gesuchte Seite gibt es nicht',
    'Update' => 'Bearbeiten',
    'Update Projekt: {name}' => 'Projekt bearbeten: {name}',
    'User ID' => 'Nutzer',
    'add' => 'hinzufügen',
];
